const mongoose = require('mongoose');

// Define a schema for storing facts from various sources
const factSchema = new mongoose.Schema({
    text: {
        type: String,
        required: true,  // Ensure every fact has a text description
        trim: true       // Remove whitespace from the beginning and end of the fact text
    },
    source: {
        type: String,
        required: true  // The source (e.g., Wikipedia, Britannica, MayoClinic) is required
    },
    sourceUrl: {
        type: String,
        required: true  // URL to the source page for the fact for verification purposes
    },
    category: {
        type: String,   // Category to classify the fact (e.g., History, Science, Health)
        required: true
    },
    retrievedDate: {
        type: Date,     // The date when the fact was retrieved
        default: Date.now  // Default to the current date
    },
    imageUrl: {
        type: String,   // URL to an image related to the fact, possibly generated by Dall-E
        required: false // This field is not required and may not always be populated
    }
});

// Export the model with the associated schema
module.exports = mongoose.model('Fact', factSchema);
